In [1]:
import pandas as pd

users = pd.read_csv("C:\\Projects & Datasets\\Python\\Analysis App\\data\\raw\\users.csv")
ads = pd.read_csv("C:\\Projects & Datasets\\Python\\Analysis App\\data\\raw\\ads.csv")
campaigns = pd.read_csv("C:\\Projects & Datasets\\Python\\Analysis App\\data\\raw\\campaigns.csv")
ad_events = pd.read_csv("C:\\Projects & Datasets\\Python\\Analysis App\\data\\raw\\ad_events.csv")

In [ ]:
#users csv EDA
users.info()
print(f"Number of null values in users DataFrame: \n{users.isnull().sum()}")
print(f"Number of duplicate rows in users DataFrame: {users.duplicated().sum()}")
users.head(5)

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      10000 non-null  str
 1   user_gender  10000 non-null  str
 2   user_age     10000 non-null  int64
 3   age_group    10000 non-null  str
 4   country      10000 non-null  str
 5   location     10000 non-null  str
 6   interests    10000 non-null  str
dtypes: int64(1), str(6)
memory usage: 1.0 MB
Number of null values in users DataFrame:
user_id        0
user_gender    0
user_age       0
age_group      0
country        0
location       0
interests      0
dtype: int64
Number of duplicate rows in users DataFrame: 0

,user_id,user_gender,user_age,age_group,country,location,interests
0,a2474,Female,24,18-24,United Kingdom,New Mariomouth,"fitness, health"
1,141e5,Male,21,18-24,Germany,Danielsfort,"food, fitness, lifestyle"
2,34db0,Male,27,25-34,Australia,Vincentchester,"fashion, news"
3,20d08,Female,28,25-34,India,Lisaport,"health, news, finance"
4,9e830,Male,28,25-34,United States,Brownmouth,"health, photography, lifestyle"

In [7]:
#ads csv EDA
ads.info()
print(f"Number of null values in ads DataFrame: \n{ads.isnull().sum()}")
print(f"Number of duplicate rows in ads DataFrame: {ads.duplicated().sum()}")
ads.head(5)

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ad_id             200 non-null    int64
 1   campaign_id       200 non-null    int64
 2   ad_platform       200 non-null    str
 3   ad_type           200 non-null    str
 4   target_gender     200 non-null    str
 5   target_age_group  200 non-null    str
 6   target_interests  200 non-null    str
dtypes: int64(2), str(5)
memory usage: 17.9 KB
Number of null values in ads DataFrame:
ad_id               0
campaign_id         0
ad_platform         0
ad_type             0
target_gender       0
target_age_group    0
target_interests    0
dtype: int64
Number of duplicate rows in ads DataFrame: 0

,ad_id,campaign_id,ad_platform,ad_type,target_gender,target_age_group,target_interests
0,1,28,Facebook,Video,Female,35-44,"art, technology"
1,2,33,Facebook,Stories,All,25-34,"travel, photography"
2,3,20,Instagram,Carousel,All,25-34,technology
3,4,28,Facebook,Stories,Female,25-34,news
4,5,24,Instagram,Image,Female,25-34,news

In [11]:
#campaigns csv EDA
campaigns.info()
print(f"Number of null values in campaigns DataFrame: \n{campaigns.isnull().sum()}")
print(f"Number of duplicate rows in campaigns DataFrame: {campaigns.duplicated().sum()}")
campaigns.head(5)

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   campaign_id    50 non-null     int64
 1   name           50 non-null     str
 2   start_date     50 non-null     str
 3   end_date       50 non-null     str
 4   duration_days  50 non-null     int64
 5   total_budget   50 non-null     float64
dtypes: float64(1), int64(2), str(3)
memory usage: 4.3 KB
Number of null values in campaigns DataFrame:
campaign_id      0
name             0
start_date       0
end_date         0
duration_days    0
total_budget     0
dtype: int64
Number of duplicate rows in campaigns DataFrame: 0

,campaign_id,name,start_date,end_date,duration_days,total_budget
0,1,Campaign_1_Launch,2025-05-25,2025-07-23,59,24021.32
1,2,Campaign_2_Launch,2025-04-16,2025-07-07,82,79342.41
2,3,Campaign_3_Winter,2025-05-04,2025-06-29,56,14343.25
3,4,Campaign_4_Summer,2025-06-04,2025-08-08,65,45326.60
4,5,Campaign_5_Launch,2025-07-11,2025-08-28,48,68376.69

In [9]:
#ads events csv EDA
ad_events.info()
print(f"Number of null values in ad_events DataFrame: \n{ad_events.isnull().sum()}")
print(f"Number of duplicate rows in ad_events DataFrame: {ad_events.duplicated().sum()}")
ad_events.head(5)

<class 'pandas.DataFrame'>
RangeIndex: 400000 entries, 0 to 399999
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   event_id     400000 non-null  int64
 1   ad_id        400000 non-null  int64
 2   user_id      400000 non-null  str
 3   timestamp    400000 non-null  str
 4   day_of_week  400000 non-null  str
 5   time_of_day  400000 non-null  str
 6   event_type   400000 non-null  str
dtypes: int64(2), str(5)
memory usage: 39.4 MB
Number of null values in ad_events DataFrame:
event_id       0
ad_id          0
user_id        0
timestamp      0
day_of_week    0
time_of_day    0
event_type     0
dtype: int64
Number of duplicate rows in ad_events DataFrame: 0

,event_id,ad_id,user_id,timestamp,day_of_week,time_of_day,event_type
0,1,197,2359b,2025-07-26 00:19:56,Saturday,Night,Like
1,2,51,f9c67,2025-06-15 08:28:07,Sunday,Morning,Share
2,3,46,5b868,2025-06-27 00:40:02,Friday,Night,Impression
3,4,166,3d440,2025-06-05 19:20:45,Thursday,Evening,Impression
4,5,52,68f1a,2025-07-22 08:30:29,Tuesday,Morning,Impression

In [12]:
campaigns["start_date"] = pd.to_datetime(campaigns["start_date"])

campaigns["end_date"] = pd.to_datetime(campaigns["end_date"])

campaigns.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   campaign_id    50 non-null     int64
 1   name           50 non-null     str
 2   start_date     50 non-null     datetime64[us]
 3   end_date       50 non-null     datetime64[us]
 4   duration_days  50 non-null     int64
 5   total_budget   50 non-null     float64
dtypes: datetime64[us](2), float64(1), int64(2), str(1)
memory usage: 3.3 KB

In [14]:
ad_events["timestamp"] = pd.to_datetime(ad_events["timestamp"])

ad_events["date"] = ad_events["timestamp"].dt.date

ad_events["month"] = ad_events["timestamp"].dt.month_name()

ad_events["hour"] = ad_events["timestamp"].dt.hour

ad_events.info()
ad_events.head(5)

<class 'pandas.DataFrame'>
RangeIndex: 400000 entries, 0 to 399999
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   event_id     400000 non-null  int64
 1   ad_id        400000 non-null  int64
 2   user_id      400000 non-null  str
 3   timestamp    400000 non-null  datetime64[us]
 4   day_of_week  400000 non-null  str
 5   time_of_day  400000 non-null  str
 6   event_type   400000 non-null  str
 7   date         400000 non-null  object
 8   month        400000 non-null  str
 9   hour         400000 non-null  int32
dtypes: datetime64[us](1), int32(1), int64(2), object(1), str(5)
memory usage: 41.3+ MB

,event_id,ad_id,user_id,timestamp,day_of_week,time_of_day,event_type,date,month,hour
0,1,197,2359b,2025-07-26 00:19:56,Saturday,Night,Like,2025-07-26,July,0
1,2,51,f9c67,2025-06-15 08:28:07,Sunday,Morning,Share,2025-06-15,June,8
2,3,46,5b868,2025-06-27 00:40:02,Friday,Night,Impression,2025-06-27,June,0
3,4,166,3d440,2025-06-05 19:20:45,Thursday,Evening,Impression,2025-06-05,June,19
4,5,52,68f1a,2025-07-22 08:30:29,Tuesday,Morning,Impression,2025-07-22,July,8

In [15]:
#saving changes to new csv files
users.to_csv("C:\\Projects & Datasets\\Python\\Analysis App\\data\\processed\\users.csv", index=False)
ads.to_csv("C:\\Projects & Datasets\\Python\\Analysis App\\data\\processed\\ads.csv", index=False)
campaigns.to_csv("C:\\Projects & Datasets\\Python\\Analysis App\\data\\processed\\campaigns.csv", index=False)
ad_events.to_csv("C:\\Projects & Datasets\\Python\\Analysis App\\data\\processed\\ad_events.csv", index=False)